version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - ZEROTIER_ACCESS_KEY=${ZEROTIER_ACCESS_KEY}
      - ZEROTIER_NODE_ID=${ZEROTIER_NODE_ID}
      - ZEROTIER_GENERAL_NET_ID=${ZEROTIER_GENERAL_NET_ID}
    volumes:
      - ./database:/app/data
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=http://light-candle.bnr.la:3000
    ports:
      - "8080:80"